# Generated by Django 5.2.1 on 2025-12-17 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schema', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='DynamicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('schema_def', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelsApp.dynamicschema')),
            ],
        ),
    ]
